Perkitw2 all template page
BIT-Studio-OP/CraftMyPortfolio pull request #83
Opened 2023-09-04 01:10 UTC by Perkitw2

Added two templates and started on updating the templates page to a grid to display the templates.

2023-09-04 08:03 UTC, Dani-op requested changes
Hi Tyler,
It appears that you inadvertently pushed the example.env file containing sensitive credentials. Since the project is open source, it is crucial to avoid including any sensitive information in pull requests, as it can make the project vulnerable to unauthorized access.

2023-09-04 09:11 UTC, Dani-op commented
> Hi Tyler, It appears that you inadvertently pushed the example.env file containing sensitive credentials. Since the project is open source, it is crucial to avoid including any sensitive information in pull requests, as it can make the project vulnerable to unauthorized access.

Ī have updated the example.env file to remove sensitive information.

2023-09-20 14:32 UTC, Dani-op requested changes

2023-10-26 00:03 UTC, Jakeclearwater approved these changes
Looks good, fix merge conflict and merge today so we can get staging working

2023-10-26 00:05 UTC, merged